LANGUAGES = {
    "TR": {
        # --- Retrosynthesis route names & mechanisms -------------------------------------
        # retro.py emits these in English (it is UI-agnostic); the key IS the English string
        # so _() translates it here and falls through unchanged for EN. Keep in sync with
        # retro.py's "type"/"mechanism" literals -- tests/test_retro.py lists them.
        "Polyester": "Poliester",
        "Polyamide": "Poliamid",
        "Polyimide": "Poliimid",
        "Polyurea": "Poliüre",
        "Polyurethane": "Poliüretan",
        "Polycarbonate": "Polikarbonat",
        "Polyether": "Polieter",
        "Polythioester": "Politiyoester",
        "Polythioether / polysulfide": "Politiyoeter / polisülfür",
        "Polyimine (azomethine)": "Poliimin (azometin)",
        "Polysiloxane (silicone)": "Polisiloksan (silikon)",
        "Polyester (AB / hydroxy-acid)": "Poliester (AB / hidroksi-asit)",
        "Polyamide (AB / amino-acid)": "Poliamid (AB / amino-asit)",
        "Poly(arylene ether)": "Poli(arilen eter)",
        "Condensation (AB monomer)": "Kondenzasyon (AB monomeri)",
        "Vinyl / addition polymer": "Vinil / katılma polimeri",
        "Vinyl / addition copolymer": "Vinil / katılma kopolimeri",
        "Vinyl / diene addition polymer": "Vinil / dien katılma polimeri",
        "Poly(alkenylene) (ROMP/ADMET)": "Poli(alkenilen) (ROMP/ADMET)",
        "Poly(xylylene) (parylene)": "Poli(ksililen) (parilen)",
        "Poly(arylene) (aryl-aryl coupling)": "Poli(arilen) (aril-aril kenetlenmesi)",
        " (branched/crosslinked)": " (dallanmış/çapraz bağlı)",
        "Step-growth condensation": "Basamaklı kondenzasyon polimerizasyonu",
        "Poly-condensation (cyclo-imidisation)": "Polikondenzasyon (siklo-imidleşme)",
        "Step-growth (isocyanate + amine)": "Basamaklı polimerizasyon (izosiyanat + amin)",
        "Poly-addition (isocyanate + alcohol)": "Poli-katılma (izosiyanat + alkol)",
        "Condensation / transesterification": "Kondenzasyon / transesterleşme",
        "Self-condensation of a hydroxy-acid": "Hidroksi-asidin kendi kendine kondenzasyonu",
        "Self-condensation of an amino-acid": "Amino-asidin kendi kendine kondenzasyonu",
        "Oxidative coupling / SNAr of a phenol": "Fenolün oksidatif kenetlenmesi / SNAr",
        "Self-condensation of an AB monomer": "AB monomerinin kendi kendine kondenzasyonu",
        "Condensation of diols / ring-opening of epoxide":
            "Diollerin kondenzasyonu / epoksit halka açılması",
        "Step-growth (acid/thiol or thioacid + ...)":
            "Basamaklı polimerizasyon (asit/tiyol veya tiyoasit + ...)",
        "Dithiol + dihalide / thiol-ene / ring-opening":
            "Ditiyol + dihalojenür / tiyol-en / halka açılması",
        "Condensation of a dialdehyde/diketone + diamine (Schiff base)":
            "Dialdehit/diketon + diamin kondenzasyonu (Schiff bazı)",
        "Hydrolysis/condensation of a dichlorosilane (or ROP of a cyclosiloxane)":
            "Diklorosilanın hidrolizi/kondenzasyonu (veya siklosiloksanın halka açılmalı polimerizasyonu)",
        "Chain-growth (radical / ionic addition)":
            "Zincir polimerizasyonu (radikalik / iyonik katılma)",
        "Chain-growth addition of olefin monomer(s)":
            "Olefin monomer(ler)inin zincir katılma polimerizasyonu",
        "1,4-addition of a 1,3-diene (rubber)": "1,3-dienin 1,4-katılması (kauçuk)",
        "Ring-opening metathesis of a cyclic olefin (or ADMET diene)":
            "Halkalı olefinin halka açılmalı metatezi (veya ADMET dien)",
        "Polymerisation of an o-/p-quinodimethane (from a [2.2]cyclophane)":
            "o-/p-kinodimetanın polimerizasyonu ([2.2]siklofandan)",
        "Transition-metal coupling (Suzuki / Yamamoto)":
            "Geçiş metali kenetlenmesi (Suzuki / Yamamoto)",
        "; crosslinked/branched at the extra connection point(s)":
            "; ek bağlantı noktalarında çapraz bağlı/dallanmış",
        # --------------------------------------------------------------------------------
        "Kompleks Kondenzasyon Polimeri": "Kompleks Kondenzasyon Polimeri",
        "Özel Sentez (AI Analizi Önerilir)": "Özel Sentez (AI Analizi Önerilir)",
        "Fonksiyonel Grup A": "Fonksiyonel Grup A",
        "Fonksiyonel Grup B": "Fonksiyonel Grup B",
        "Uç grupların reaksiyonu": "Uç grupların reaksiyonu",
        "Vinil Polimerizasyonu (Katılma)": "Vinil Polimerizasyonu (Katılma)",
        "Radikalik": "Radikalik",
        "Çift bağ açılması": "Çift bağ açılması",
        "Asit + Amin -> Amid + Su": "Asit + Amin -> Amid + Su",
        "Polyester Sentezi": "Polyester Sentezi",
        "Kademeli Polimerizasyon": "Kademeli Polimerizasyon",
        "Dikarboksilik Asit": "Dikarboksilik Asit",
        "Diol": "Diol",
        "Asit + Alkol -> Ester + Su": "Asit + Alkol -> Ester + Su",
        "Poliamid (Nylon) Sentezi": "Poliamid (Nylon) Sentezi",
        "Polikondenzasyon": "Polikondenzasyon", 
        "İzosiyanat + Alkol -> Üretan Bağı": "İzosiyanat + Alkol -> Üretan Bağı",
        "Diizosiyanat (Örn: TDI, MDI)": "Diizosiyanat (Örn: TDI, MDI)",
        "Diol / Polyol": "Diol / Polyol",
        "Poliladisyon": "Poliladisyon",
        "Poliüretan (PU) Sentezi": "Poliüretan (PU) Sentezi",
        "İzosiyanat + Amin -> Üre Bağı (Yan ürün yok)": "İzosiyanat + Amin -> Üre Bağı (Yan ürün yok)",
        "Diamin (Diamine)": "Diamin (Diamine)",
        "Diizosiyanat (Diisocyanate)": "Diizosiyanat (Diisocyanate)",
        "Basamaklı Polimerizasyon (Hızlı)": "Basamaklı Polimerizasyon (Hızlı)",
        "Poliüre (Polyurea) Sentezi": "Poliüre (Polyurea) Sentezi",
        "Dianhidrit + Diamin -> Poliimid": "Dianhidrit + Diamin -> Poliimid",
        "Dianhidrit": "Dianhidrit",
        "Diamin": "Diamin",
        "Siklo-dehidrasyon": "Siklo-dehidrasyon",
        "Poliimid Sentezi": "Poliimid Sentezi",
        "Generation": "Jenerasyon",
        "Çeşitlilik" : "Çeşitlilik",
        "Uretilen Polimer": "Üretilen Polimer",
        "Hedeflenen": "Hedeflenen",
        "yeşil_score": "Yeşil Skor",
        "predicted_monomers_image_caption": "Modelin Önerdiği Yapı Taşları",
        "msg_predicting": "Monomerler Tahmin Ediliyor",
        "msg_success":"Monomer Tahmini Başarılı!",
        "retro_structural": "1. Yapısal Ayrıştırma",
        "retro_t5_pred": "2. T5-Model Tahmini",
        "btn_predict_monomer": "Monomerleri Tahmin Et",
        "retro_t5_desc": "Eğittiğimiz model, moleküler yapıyı analiz ederek monomerleri tahmin ediyor.",
        "retro_auto_failed": "Otomatik analiz yapılamadı. Lütfen önerilen monomerleri manuel olarak inceleyin.",
        "kayitli_degil": "Ticari kayit yok",
        "control": "Kontrol",
        "commercial_check": "#### Ticari Bulunabilirlik (PubChem)",
        "baslangic_monomerleri":"**Olası Başlangıç Monomerleri:**",
        "yontem": "Yöntem",
        "mechanism": "Mekanizma",
        "retro_analysis_header": "Retrosentez Analizi",
        "retro_auto_failed": "Otomatik analiz yapılamadı. Lütfen önerilen monomerleri manuel olarak inceleyin.",
        "retro_rule_method": "Kural tabanlı omurga ayrıştırması ile bulunan gerçek monomer yapıları (T5 modeline bağlı değildir).",
        "retro_tentative": "Ayrıştırma yapıldı ancak doğrulama testini (fonksiyonel grup / atom korunumu) geçemedi — monomerler yaklaşık/eksik olabilir.",
        "retro_named_only": "Bu polimerin bilinen bir polimerleşme bağı yok; yalnızca olası mekanizma tahmini gösteriliyor, kesin monomer yapısı çıkarılamadı.",
        "get_free_api": "Ücretsiz API Key Almak İçin Tıkla(https://aistudio.google.com/app/apikey)",
        "chatbot_no_api": "Bu polimer hakkında detaylı kimyasal yorum almak için sol menüden **Google Gemini API Key** girmelisiniz.",
        "chatbot_desc": "PPolimer yapısı ve tahmin edilen özellikler hakkında detaylı kimyasal yorum almak için AI destekli ChatBot'u kullanın.",
        "download":"İndir",
        "report_ready": "Rapor hazır!",
        "report_getting_ready": "Rapor derleniyor... Lütfen bekleyin.",
        "pdf_report_info": "Bu rapor; tüm tahminleri, molekül yapısını, AI yorumlarını ve varsa sentez planını içerir.",
        "pdf_report": "PDF Raporu",
        "how_to_read": """                **Bu Grafikler Nasıl Okunur?**
                * **Yakınsama (Üst):** Yeşil çizgi sürekli düşmeli ve bir noktada yataylaşmalıdır (Plateau). Mavi çizgi yeşile çok yaklaşırsa popülasyon "öğrenmiş" demektir.
                * **Çeşitlilik (Alt):** Kırmızı çizginin sıfıra çok hızlı düşmemesi gerekir. Sıfıra düşerse model "Erken Yakınsama (Premature Convergence)" tuzağına düşmüştür; yani arama uzayını yeterince taramadan bir sonuca saplanmıştır.""",
        "genetic_algorithm_report": "Genetik Algoritma Performans Raporu",
        "novelty_explanation": "*Benzerlik, Tanimoto İndeksi (Morgan Fingerprints) kullanılarak hesaplanmıştır.*",
        "closest_sim": "En yakın benzerlik",
        "novel":"**KEŞİF:** Bu yapı eğitim setinde yok. Özgün bir tasarım.",
        "benzer_yapi": "Benzer Yapıyı Gör",
        "turev": "",
        "benzer":"",
        "copy":"",
        "kayitli": "Bu molekül PubChem'de kayıtlı:",
        "code":"kodu",
        "radar_warning":"Radar grafiği için en az 3 özellik (Örn: Tg, LOI, CTE) seçmelisiniz.",
        "takip_disi":"Takip Dışı",
        "water": "Su",
        "metanol": "Metanol",
        "etanol": "Etanol",
        "THF": "Tetrahidrofuran (THF)",
        "diklorometan": "Diklorometan (DCM)",
        "aseton": "Aseton (Polar Aprotik)",
        "kloroform": "Klorofom",
        "etil asetat": "Etil Asetat",
        "toluen": "Toluen (Aromatik)",
        "dietil_eter": "Dietil Eter",
        "hekzan": "Hekzan",
        "solubility_explanation_1": "*Analiz, 'Benzer Benzeri Çözer' ilkesine göre Polimer ",
        "solubility_explanation_2":" ve Çözücü arasındaki Hansen Parametresi farkına dayanır.*",
        "no_solubility":"Bu polimer çok dirençli görünüyor (veya çok özel bir çözücü gerektiriyor).",
        "aromatic":"Yüksek Aromatiklik (Zor parçalanma)",
        "halogen":"adet Halojen atomu (Kalıcılık/Toksisite riski)",
        "ether":"Eter grubu (Hidrofilik özellik)",
        "amide":"Amid bağı (Biyo-bozunurluk potansiyeli)",
        "ester":"Ester bağı (Hidroliz olabilir)",
        "easy": "Kolay",
        "hard": "Zor",
        "survival_rate": "Canlılık Oranı %",
        "best_fitness": "En İyi Hata",
        "avg_fitness": "Ortalama (Valid)",
        "gen": "Nesil",
        "diversity_chart": "Popülasyon Çeşitliliği",
        "convergence_chart": "Yakınsama Analizi",
        "evolution_panel": "### 🧬 Evrimsel Süreç İzleme Paneli",
        "api_key_explanation": "AI yorumu almak için https://aistudio.google.com/app/apikey adresinden ücretsiz anahtar alabilirsiniz.",
        "target": "Hedef",
        # Genel Başlıklar
        "app_subtitle": "Yapay Zeka Destekli Polimer Tasarlayıcısı",
        "sidebar_target_selection": "Hedef Seçimi",
        "sidebar_included_props": "Dahil Edilecek Özellikler",
        "sidebar_target_values": "Hedef Değerler",
        "sidebar_generations": "Evrim Nesli Sayısı",
        "sidebar_strategy": "Algoritma Stratejisi",
        "manual_title": "Manuel Polimer Analizi",
        "manual_desc": "Genetik algoritmayı çalıştırmadan, kendi polimerinizin (SMILES) özelliklerini ve retrosentezini hızlıca görün.",
        "manual_input_label": "Polimer SMILES kodu (örn: *CC(c1ccccc1)*):",
        "manual_btn": "Analiz Et",
        "manual_invalid": "Geçersiz SMILES kodu. Lütfen kimyasal sözdizimini kontrol edin.",
        "xtb_header": "Kuantum Çapraz Kontrol (xtb / GFN2)",
        "xtb_desc": "Bağımsız bir yarı-deneysel kuantum yöntemiyle (GFN2-xTB) bant aralığını ve elektronik kutuplanabilirliği hesaplar. Yalnızca yerelde xtb kuruluysa görünür.",
        "xtb_btn": "xtb ile Doğrula",
        "xtb_running": "xtb çalışıyor (oligomerler 3B'ye gömülüp hesaplanıyor)…",
        "xtb_failed": "xtb kontrolü tamamlanamadı",
        "xtb_gap_label": "xtb bant aralığı (sonsuz zincir)",
        "xtb_model_label": "Model tahmini",
        "xtb_polar_label": "Elektronik kutuplanabilirlik yoğunluğu (α/V)",
        "xtb_polar_hint": "Yüksek ⇒ yüksek kırılma indisi ve dielektrik (sıralama göstergesi)",
        "xtb_note": "GFN2 yarı-deneyseldir; mutlak değeri eğitimdeki DFT'den sistematik olarak farklıdır — sıralama uyumu esas ölçüttür. Ayrıntılar: validation/XTB_VALIDATION.md",
        "verify_title": "Bu Sonucu Doğrula (Kuantum)",
        "verify_desc": "Optimal polimerin tahminlerini BAĞIMSIZ yöntemlerle çapraz kontrol edin: van Krevelen grup katkısı (çözünürlük, Hansen, kırılma indisi) her zaman; xtb kuruluysa GFN2-xTB kuantum (bant aralığı, dielektrik alt sınırı) da eklenir.",
        "verify_btn": "Bağımsız Yöntemlerle Doğrula",
        "verify_none": "Bu polimer için bağımsız olarak doğrulanabilir bir özellik bulunamadı.",
        "verify_independent": "bağımsız tahmin",
        "verify_floor": "fiziksel alt sınır",
        "blend_misc_miscible": "karışabilir",
        "blend_misc_borderline": "sınırda",
        "blend_misc_immiscible": "karışmaz",
        "blend_misc_unknown": "belirlenemedi",
        "blend_misc_note_miscible": "Çözünürlük parametreleri birbirine yakın; tek bir Tg beklenir.",
        "blend_misc_note_borderline": "Kısmi karışabilirlik / zayıf arafaz; genişlemiş ya da birbirine yakın iki Tg beklenir.",
        "blend_misc_note_immiscible": "Faz ayrımı; iki ayrı Tg beklenir. Bu mutlaka kötü değildir — toklaştırılmış ticari malzemelerin çoğu dağılmış bir kauçuk faza dayanır.",
        "blend_misc_note_crystalline": "Çözünürlük parametreleri uyuşuyor ANCAK iki bileşen de yarı-kristalin görünüyor: ayrı kristalin fazlar katı halde genelde korunur (PE/PP klasik örnektir). Soğumada faz ayrımı beklenir.",
        "blend_misc_note_unknown": "Bileşenlerden biri için çözünürlük parametreleri hesaplanamadı.",
        "blend_misc_caveat_specific": "DİKKAT: Burada spesifik bir etkileşim mümkün ({inter}); çözünürlük parametreleri bunu göremez ve bu etkileşim karışabilirliği zorlayabilir.",
        "blend_inter_pipi": "aromatik eter + aromatik halka (π-π, ör. PPO/PS)",
        "blend_inter_dipole": "karbonil + halojenli karbon (dipol/H-bağı, ör. PMMA/PVDF)",
        "blend_inter_hbond": "hidroksil + karbonil (H-bağı)",
        "blend_rule_fox": "Fox denklemi (karışabilir)",
        "blend_rule_phasesep": "faz ayrımı",
        "blend_rule_specvol": "toplanabilir özgül hacim",
        "blend_rule_ll": "Lorentz-Lorenz (hacim kesri)",
        "blend_rule_semilog": "yarı-logaritmik toplanabilir (karışabilir)",
        "blend_rule_maxwell": "Maxwell modeli (dağılmış faz)",
        "blend_rule_volfrac": "hacim kesrine göre toplanabilir",
        "blend_rule_wtadd": "ağırlıkça toplanabilir",
        "blend_rule_weakest": "en kararsız bileşen",
        "blend_rule_notavg": "ortalaması alınmaz",
        "blend_rule_rom": "karışım kuralı (paralel sınır)",
        "blend_note_singletg": "tek Tg beklenir",
        "blend_note_twotg": "iki ayrı Tg korunur: {tgs}",
        "blend_note_hazy": "faz ayrımlı harmanlar ışığı saçar ve genelde mattır",
        "blend_note_continuous": "sürekli faz = bileşen {n}",
        "blend_note_loi": "DİKKAT: Aleve dayanıklılık çoğu zaman toplanabilir değildir (sinerji/antagonizma); yalnızca gösterge olarak değerlendirin.",
        "blend_note_td": "bozunma başlangıcı en zayıf bileşen tarafından belirlenir",
        "blend_note_tm_each": "her kristalin faz kendi Tm'ini korur: {tms}",
        "blend_note_bounds": "seri sınır {ser}; gerçek değer iki sınır arasındadır ve morfolojiye bağlıdır",
        "blend_mode": "Birleştirme türü",
        "blend_mode_blend": "Harman (fiziksel karışım)",
        "blend_mode_random": "Rastgele kopolimer",
        "blend_mode_alternating": "Ardışık kopolimer",
        "blend_mode_block": "Blok kopolimer",
        "copo_built_unit": "Oluşturulan A-B tekrar birimi (doğrudan modellerle tahmin edildi):",
        "copo_rule_direct": "doğrudan tahmin (gerçek tekrar birimi)",
        "copo_rule_fox": "Fox denklemi (tek faz)",
        "copo_rule_wtadd": "ağırlıkça toplanabilir",
        "copo_rule_semilog": "yarı-logaritmik toplanabilir",
        "copo_rule_weakest": "en kararsız bileşen",
        "copo_rule_twophase": "iki faz (mikrofaz ayrımı)",
        "copo_rule_nocryst": "kristallik bozulur",
        "copo_note_alternating_exact": "Ardışık kopolimerde A-B çifti gerçek bir tekrar birimidir; bu yüzden birim oluşturulup doğrudan modellere verildi — bu bir karışım tahmini değil, doğrudan bir tahmindir.",
        "copo_note_build_failed": "A-B tekrar birimi oluşturulamadı (bileşenlerden biri uygun bir tekrar birimi değil).",
        "copo_note_block_sep": "Bloklar mikrofaz ayrımına uğrar: iki ayrı Tg ve alan (domain) morfolojisi beklenir. SBS'in termoplastik elastomer olmasının nedeni budur.",
        "copo_note_block_single": "Bloklar karışabilir görünüyor: tek faz ve tek Tg beklenir.",
        "copo_note_two_tg": "iki ayrı Tg korunur: {tgs}",
        "copo_note_td": "bozunma başlangıcı en zayıf bileşen tarafından belirlenir",
        "copo_note_tm_suppressed": "Komonomer katılımı zincir düzenliliğini bozar; erime noktası ortalanmaz, BASTIRILIR (hatta kaybolur). EVA'nın PE'den esnek olmasının nedeni budur.",
        "copo_note_tm_each": "her kristalin faz kendi Tm'ini korur: {tms}",
        "tab_blend": "Harman",
        "blend_header": "Polimer Harmanı / Alaşımı",
        "blend_desc": "Gerçek malzemeler genelde saf homopolimer değil, harman veya alaşımdır (Noryl = PS/PPO, ABS, PC/ABS). Bu sekme bulunan polimeri ticari bir polimerle veya başka bir adayla harmanlar; karışabilirliği tarar ve harman özelliklerini standart karışım kurallarıyla tahmin eder.",
        "blend_partner": "Harman ortağı",
        "blend_custom": "veya kendi SMILES'inizi girin (opsiyonel)",
        "blend_weight": "Ana polimerin ağırlıkça oranı (%)",
        "blend_miscibility": "Karışabilirlik",
        "blend_confidence": "güven",
        "blend_props": "Harman özellikleri",
        "blend_value": "Değer",
        "blend_rule": "Kullanılan kural",
        "blend_note": "Not",
        "blend_candidate": "Aday",
        "blend_download": "Harman verisini CSV indir",
        "blend_screen_caveat": "Bu bir TARAMA'dır, kanıt değil: çözünürlük parametresi yalnızca entalpik terimi görür. Spesifik etkileşimlerle karışan çiftleri (PS/PPO π-π, PMMA/PVDF dipol) yanlış sınıflayabilir — bu durumlar ayrıca işaretlenir. Bilinen 10 harmanda 7/10 doğru.",
        "cr_bad_smiles": "SMILES geçerli bir moleküle çözümlenemiyor.",
        "cr_need_two_stars": "Bir tekrar biriminde iki bağlantı noktası '*' olmalıdır.",
        "cr_multistar": "{n} bağlantı noktası: bu doğrusal bir tekrar birimi değil, bir dallanma/çapraz bağ düğümüdür. Özellikler doğrusal zincir varsayımıyla hesaplanır ve ağ oluştuğunda değişir.",
        "cr_acid_alcohol": "Hem -COOH hem -OH taşıyor: işleme sırasında kendi kendine esterleşir, dolayısıyla kararlı bir tekrar birimi değildir (dallanır/çapraz bağlanır veya polimerleşmeye devam eder).",
        "cr_acid_amine": "Hem -COOH hem -NH taşıyor: ısıtıldığında kendi kendine amidleşir; kararlı bir tekrar birimi değildir.",
        "cr_epoxide": "Epoksit ile bir nükleofilin (-OH/-NH/-COOH) birlikte bulunması halka açılmasına ve çapraz bağlanmaya yol açar.",
        "cr_isocyanate": "Serbest izosiyanat çok reaktif ve neme duyarlıdır; izole bir polimerde kalıcı olmaz.",
        "cr_peroxide": "Peroksit bağı: termal olarak kararsız/patlayıcı.",
        "cr_nn_bond": "Halkasız N-N bağı: genellikle termal olarak zayıftır.",
        "cr_tm_amorphous": "Tm değeri veriliyor ({tm} °C) ancak bu yapı AMORF görünüyor (hacimli yan grup / engelli omurga). Amorf bir polimerin erime noktası yoktur — Tm'i burada anlamsız kabul edin ve Tg'yi kullanın. Taktisite bir tekrar biriminde kodlanmadığı için bu yapısal bir çıkarımdır.",
        "cr_tm_plausible": "Omurga kristalleşebilecek kadar düzenli görünüyor, dolayısıyla Tm makul — ancak kristallik taktisiteye ve termal geçmişe de bağlıdır; bunlar tekrar biriminde ifade edilemez.",
        "cr_tg_above_tm": "Tg ({tg} °C) Tm'in ({tm} °C) altında değil; yarı-kristalin bir polimerde daima Tg < Tm olur, dolayısıyla iki tahminden en az biri hatalıdır.",
        "cr_tg_above_td": "Tg ({tg} °C), Td'nin ({td} °C) üzerinde: bir polimer bozunduğu sıcaklığın üstünde yumuşayamaz; dolayısıyla bu iki tahminden biri bu yapı için hatalıdır.",
        "cr_tm_above_td": "Tm ({tm} °C), Td'nin ({td} °C) üzerinde: polimer erimeden önce bozunur, yani kullanılabilir bir eriyik penceresi yoktur (ve tahminlerden biri muhtemelen hatalıdır).",
        "cr_boyer_beaman": "Tg/Tm = {ratio} (K cinsinden); Boyer-Beaman kuralına göre çoğu polimer 0.5-0.8 aralığındadır, bu çift alışılmadık.",
        "cr_halogen_loi": "Buradaki yüksek LOI halojen içeriğinden geliyor. Halojenli aleve dayanıklılık etkilidir ancak birçok pazarda mevzuatla kısıtlanmaktadır (ve Br/Cl yanmada aşındırıcı HX açığa çıkarır).",
        "cr_very_aromatic": "Yoğun aromatik: çözünürlüğü düşük ve işleme sıcaklığı çok yüksek olabilir; eriyikten işleme mümkün olmayabilir.",
        "cr_big_unit": "Büyük tekrar birimi ({mw} g/mol): çok adımlı bir monomer sentezi gerektirir.",
        "chem_review_title": "Kimyager Değerlendirmesi",
        "chem_review_desc": "Modeller her yapı için bir sayı üretir; bunların bazıları o polimer için fiziksel anlam taşımaz (amorf bir polimer için erime noktası gibi). Aşağıdaki notlar bu durumları ve tekrar birimi olarak kararsız olabilecek grupları işaretler. Bunlar red değil, uyarıdır.",
        "topn_title": "Diğer güçlü adaylar",
        "topn_desc": "En düşük hatalı polimer her zaman yapılması en kolay olan değildir. Bu liste, hedeflerinize yakın diğer adayları gösterir — bazıları daha kolay sentezlenebilir (düşük SA skoru) veya daha tanıdık kimyaya sahiptir.",
        "topn_download": "Aday listesini CSV indir",
        "mae_heldout": "Ayrılmış test kümesinde (%20 hold-out) ölçülen gerçek örneklem-dışı hata; eğitim dağılımı içinde olduğu için golden-set sayısından biraz iyimserdir.",
        "mae_molecule": "Bu MOLEKÜLE özel belirsizlik: modelin kendi iç dağılımından hesaplandı (bu özellik için hatayı gerçekten öngördüğü doğrulandı). ＊ işareti molekül-bazlı olduğunu gösterir.",
        "stay_in_domain": "Modelin güven alanında kal",
        "stay_in_domain_help": "Açıkken GA, eğitim verisinden çok uzaklaşan (tahminlerin güvenilmez olduğu) polimerleri cezalandırır. VARSAYILAN KAPALI: yenilikçiliği azaltır, ama tahminleri daha güvenilir kılar.",
        "stay_in_domain_note": "Denge: daha güvenilir tahminler, daha az yenilikçi yapılar.",
        "pubchem_search": "PubChem'de ara",
        "verify_branched": "Bu tekrar birimi dallanmış (2'den fazla bağlantı noktası). xtb kontrolü ana zincir üzerinden yapılır; dallar uç kapatılarak çıkarılır. van Krevelen tüm atomları kullanır.",
        "verify_note": "✅ tutarlı · ⚠️ sınırda · ❌ ayrışıyor. Bant aralığı kalibre edilmiş mutlak bir kontroldür (±0.9 eV, xtb). Kırılma indisi/çözünürlük/Hansen grup-katkısı tahminleridir (van Krevelen). Kalan özelliklerin (Tg, Tm, Td, CTE…) tek polimer için güvenilir bağımsız oracle'ı yok — modele golden-set hata payıyla güvenin. Ayrıntılar: validation/",
        "mae_legend": "± değerleri, YENİ bir polimer için beklenen tipik hatadır (güven aralığı değildir). Kaynak için sayının üzerine gelin.",
        "mae_gold": "Örneklem dışı: 18 kanonik referans polimerde ölçülen ortalama mutlak hata (dürüst tahmin).",
        "mae_insample": "Yalnızca örneklem içi/ayrılmış test hatası — iyimserdir, alt sınır olarak görün.",
        "ad_title": "Uygulanabilirlik Alanı",
        "ad_ok": "polimer eğitim verisine benziyor, tahminler normal doğrulukta",
        "ad_warn_edge": "bu polimer eğitim verisinin sınırında. Mutlak değerleri temkinli kullanın; yön/sıralama daha güvenilirdir.",
        "ad_warn_out": "bu polimer eğitim dağılımının DIŞINDA (ekstrapolasyon). Özellikle EPS alan dışında ortalamaya kaçar — mutlak değerlere güvenmeyin, yön/sıralamayı kullanın ve mümkünse doğrulama panelini çalıştırın.",
        "ad_similarity": "eğitim verisine en yakın benzerlik",
        "retro_exact": "Tam eşleşme: monomer yeniden polimerleştiğinde bu tekrar birimini birebir veriyor.",
        "retro_approx": "Yaklaşık: monomer en yakın gerçekçi seçenek; yeniden polimerleşince küçük bir farkla benzer birim veriyor.",
        "btn_download_report": "Tam Raporu İndir (.txt)",
        "start_from": "Kendi polimerinden başla (SMILES, opsiyonel)",
        "start_from_help": "Bir SMILES girerseniz GA sıfırdan başlamak yerine bu polimeri iyileştirir. Boş bırakılırsa normal veri setinden başlar.",
        "start_from_invalid": "Geçersiz polimer SMILES (iki '*' bağlantı noktası gerekir) — yok sayılıyor.",
        "start_from_ok": "Başlangıç polimeri kabul edildi.",
        "start_from_compare": "Başlangıç polimerinize göre değişim",
        "start_from_prop": "Özellik",
        "start_from_before": "Başlangıç",
        "start_from_after": "Sonuç",
        "random_seed": "Rastgelelik Tohumu (0 = rastgele)",
        "random_seed_help": "0 dışında bir değer verirseniz aynı ayarlarla çalıştırma her seferinde aynı sonucu üretir (tekrarlanabilirlik).",
        "ga_params_title": "Gelişmiş GA Parametreleri",
        "ga_pop_size": "Popülasyon Boyutu",
        "ga_pop_size_help": "Her nesildeki birey (polimer) sayısı. Daha büyük = daha iyi arama ama daha yavaş. (NSGA-II için 4'ün katına yuvarlanır.)",
        "ga_cxpb": "Çaprazlama Olasılığı",
        "ga_cxpb_help": "İki ebeveynin yan gruplarını değiştirme (crossover) olasılığı.",
        "ga_fragpb": "Fragman Mutasyonu Olasılığı",
        "ga_fragpb_help": "Hedefe yönelik kimyasal grup ekleme/omurga bağı ekleme olasılığı (ana mutasyon operatörü).",
        "ga_mutpb": "SELFIES Mikro-mutasyonu",
        "ga_mutpb_help": "Küçük token düzeyinde SELFIES mutasyonu olasılığı (keşif için düşük tutulur).",
        "ga_chempb": "Reaksiyon Mutasyonu",
        "ga_chempb_help": "SMARTS reaksiyon tabanlı mutasyon olasılığı.",
        "ga_removepb": "Grup Budama Olasılığı",
        "ga_removepb_help": "Yapı-koruyucu uç grup silme (halka/fonksiyonel gruba dokunmaz) olasılığı.",
        "ga_newpb": "Yeni Birey (Reseed) Olasılığı",
        "ga_newpb_help": "Çeşitlilik için rastgele yeni birey ekleme olasılığı. Yüksek değerler aramayı bozabilir.",
        "ga_tournsize": "Turnuva Boyutu",
        "ga_tournsize_help": "Seçim baskısı: daha büyük = daha hızlı yakınsama ama daha az çeşitlilik.",
        "ga_reset": "Varsayılana Sıfırla",
        "reliability_legend": "Model güvenilirliği: 🟢 yüksek · 🟡 orta · 🟠 sadece sıralama · 🔴 güvenilmez (doğrulama sonuçlarına göre)",
        "reliability_high": "Yüksek güvenilirlik — model bu özelliği veri setinde iyi tahmin ediyor.",
        "reliability_medium": "Orta güvenilirlik — kabaca doğru, mutlak değer ±belirsizlik içerir.",
        "reliability_low": "Düşük güvenilirlik — yalnızca sıralama için kullanın, mutlak değere güvenmeyin.",
        "reliability_unreliable": "Güvenilmez — bu model doğrulamada başarısız oldu (veri/etiket sorunu). Sonuca güvenmeyin.",
        "warn_unreliable": "Bu özellik(ler)in modeli güvenilmez, hedef olarak seçmek yanıltıcı olabilir:",
        "opt_mode": "Optimizasyon Yöntemi",
        "opt_mode_help": "NSGA-II: Çok amaçlı Pareto optimizasyonu; birden fazla hedef arasındaki ödünleşimleri (trade-off) korur. Ağırlıklı: Tüm hataları tek bir skorda birleştiren klasik yöntem.",
        "opt_nsga2": "NSGA-II (Pareto / Çok Amaçlı)",
        "opt_weighted": "Ağırlıklı (Tek Amaçlı)",
        "pareto_front": "Pareto Cephesi (Ödünleşim Çözümleri)",
        "pareto_desc": "Her satır, hedefler arasında farklı bir ödünleşim sunan, birbirine baskın olmayan bir polimer adayıdır.",
        "knee_note": "**⭐ Diz Noktası (Knee):** Tüm hedefleri en dengeli şekilde karşılayan çözüm. Üstte gösterilen sonuç budur.  🎯 = en düşük toplam hata (tek bir özellikte iyi ama dengesiz olabilir).",
        "knee_point": "Diz Noktası (En Dengeli)",
        "col_pick": "Seçim",
        "use_heuristic": "Sezgisel Başlangıç (Hedefe Yönelik)",
        "use_heuristic_help": "Açık: Popülasyon, hedefe uygun temel polimerlerle başlatılır (örn. düşük Tg için esnek omurgalar) ve mutasyonlar hedefe yönlendirilir. Kapalı: Klasik 'kör' başlangıç (yalnızca veri setinden rastgele).",
        "preserve_structure": "Önemli Yapıları Koru",
        "preserve_structure_help": "Açık: Mutasyonlar mevcut halkaları, aromatik sistemleri ve fonksiyonel grupları (ester, amid, imid, sülfon vb.) asla bozamaz; yalnızca ekleyebilir.",
        "sidebar_llm_settings": "LLM ChatBot Ayarları",
        "sidebar_btn_search": "Hedefi Ara",
        
        # Uyarılar ve Mesajlar
        "warn_no_target": "Lütfen optimize edilecek en az bir hedef seçin.",
        "warn_empty_pop": "Başlangıç popülasyonu boş veya geçersiz.",
        "msg_optimizing": "Genetik Algoritma Çalışıyor... Hedefler:",
        "msg_success": "✅ Optimizasyon Başarıyla Tamamlandı!",
        "msg_ai_thinking": "Yapay zeka düşünüyor...",
        
        # Özellikler (Properties)
        "prop_tg": "Tg (Camsı Geçiş Sıcaklığı)",
        "prop_td": "Td (Bozunma Sıcaklığı)",
        "prop_eps": "EPS (Dielektrik Sabiti)",
        "prop_tm": "Tm (Erime Sıcaklığı)",
        "prop_bandgap_bulk": "Bandgap Bulk (Elektriksel Band Aralığı - Bulk)",
        "prop_bandgap_chain": "Bandgap Chain (Elektriksel Band Aralığı - Zincir)",
        "prop_bandgap_crystal": "Bandgap Crystal (Elektriksel Band Aralığı - Kristal)",

        "prop_gas_perma": "Gas Permeability (Gaz Geçirgenliği)",
        "prop_refractive": "Refractive Index (Kırılma İndeksi)",
        "prop_loi": "LOI (Yanıcılık İndeksi)",
        "prop_solubility": "Çözünürlük (Hildebrand)",
        "prop_thermal_cond": "Isıl İletkenlik (Thermal Cond.)",
        "prop_cte": "Isıl Genleşme (CTE)",
        "prop_recyclability": "Kimyasal Geri Dönüşüm (Entalpi - ΔH_rop)",
        "prop_degradability": "Bozunabilirlik Skoru",
        "prop_hansen": "Hansen Çözünürlük Parametresi",
        
        # Sekmeler
        "tab_general": "Genel",
        "tab_structural": "Yapısal Analiz",
        "tab_evolution": "Evrim Geçmişi",
        "tab_report": "Raporlama",
        "tab_chatbot": "ChatBot",
        "tab_retro": "Retrosentez",
        
        # Metrikler ve Analizler
        "metric_total_error": "Toplam Hata:",
        "metric_sa_score": "Sentez Zorluğu (SA)",
        "metric_green_score": "Yeşil Skor",
        "env_analysis": "Çevresel Analiz:",
        "solubility_analysis": "Tahmini Çözünürlük Analizi",
        "soluble_in": "Çözünmesi Beklenenler:",
        "swelling_in": "Şişme / Zor Çözünme Beklenenler:",
        "radar_title": "Hedef Uyumluluk Analizi",
        
        # Sekme 2 & 3 (Yapı ve Evrim)
        "2d_structure": "2D Yapı (Teknik Çizim)",
        "3d_structure": "3D Konformasyon",
        "novelty_search": "Özgünlük Analizi (Novelty Search)",
        "similarity_to_train": "Eğitim Setine Benzerlik",
        "convergence_chart": "Yakınsama Analizi (Convergence)",
        "diversity_chart": "Popülasyon Çeşitliliği (Diversity)",
        
        # Raporlama
        "report_header": "Raporlama",
        "report_desc": "Proje verilerini CSV veya detaylı PDF raporu olarak dışa aktarabilirsiniz.",
        "btn_download_csv": "Veri Setini İndir (.csv)",
        "btn_create_pdf": "PDF Raporu Oluştur",
        
        # Retrosentez
        "retro_structural": "1. Yapısal Ayrıştırma",
        "retro_t5_pred": "2. T5-Model Tahmini",
        "btn_predict_monomer": "Monomerleri Tahmin Et",
        "proposed_monomers": "Önerilen Monomerler:"
    },
    "EN": {
        "Kompleks Kondenzasyon Polimeri": "Complex Condensation Polymer",
        "Özel Sentez (AI Analizi Önerilir)": "Special Synthesis (AI Analysis Recommended)",
        "Fonksiyonel Grup A": "Functional Group A",
        "Fonksiyonel Grup B": "Functional Group B",
        "Uç grupların reaksiyonu": "Reaction of End Groups",
        "Vinil Polimerizasyonu (Katılma)": "Vinyl Polymerization (Addition)",
        "Radikalik": "Radical",
        "Çift bağ açılması": "Double Bond Opening",
        "Asit + Amin -> Amid + Su": "Acid + Amine -> Amide + Water",
        "Polyester Sentezi": "Polyester Synthesis",
        "Kademeli Polimerizasyon": "Step-Growth Polymerization",
        "Dikarboksilik Asit": "Dicarboxylic Acid",
        "Diol": "Diol",
        "Asit + Alkol -> Ester + Su": "Acid + Alcohol -> Ester + Water",
        "Poliamid (Nylon) Sentezi": "Polyamide (Nylon) Synthesis",
        "Polikondenzasyon": "Polycondensation",
        "İzosiyanat + Alkol -> Üretan Bağı": "Isocyanate + Alcohol -> Urethane Linkage",
        "Diizosiyanat (Örn: TDI, MDI)": "Diisocyanate (e.g., TDI, MDI)",
        "Diol / Polyol": "Diol / Polyol",
        "Poliladisyon": "Polyaddition",
        "Poliüretan (PU) Sentezi": "Polyurethane (PU) Synthesis",
        "İzosiyanat + Amin -> Üre Bağı (Yan ürün yok)": "Isocyanate + Amine -> Urea Linkage (No Byproduct)",
        "Diamin (Diamine)": "Diamine",
        "Diizosiyanat (Diisocyanate)": "Diisocyanate",
        "Basamaklı Polimerizasyon (Hızlı)": "Step-Growth Polymerization (Fast)",
        "Poliüre (Polyurea) Sentezi": "Polyurea Synthesis",
        "Dianhidrit + Diamin -> Poliimid": "Dianhydride + Diamine -> Polyimide",
        "Dianhidrit": "Dianhydride",
        "Diamin": "Diamine",
        "Siklo-dehidrasyon": "Cyclo-dehydration",
        "Poliimid Sentezi": "Polyimide Synthesis",
        "Generation": "Generation",
        "Çeşitlilik" : "Diversity",
        "Uretilen Polimer": "Produced Polymer",
        "Hedeflenen": "Targeted",
        "yeşil_score": "Green Score",
        "predicted_monomers_image_caption": "Model's Proposed Building Blocks",
        "msg_predicting": "Predicting Monomers",
        "msg_success":"Monomer Prediction Successful!",
        "retro_structural": "1. Structural Decomposition",
        "retro_t5_pred": "2. T5-Model Prediction",
        "btn_predict_monomer": "Predict Monomers",
        "retro_t5_desc": "Our trained model analyzes the molecular structure to predict the monomers.",
        "retro_auto_failed": "Automatic analysis failed. Please review the proposed monomers manually.",
        "kayitli_degil": "No commercial record",
        "control": "Check",
        "commercial_check": "#### Commercial Availability Check (PubChem)",
        "baslangic_monomerleri":"**Possible Starting Monomers:**",
        "yontem": "Method",
        "mechanism": "Mechanism",
        "retro_analysis_header": "Retrosynthesis Analysis",
        "retro_auto_failed": "Automatic analysis failed. Please review the proposed monomers manually.",
        "retro_rule_method": "Real monomer structures from rule-based backbone disconnection (does not rely on the T5 model).",
        "retro_tentative": "A disconnection was found but it failed the verification test (functional-group / atom-conservation) — the monomers may be approximate or incomplete.",
        "retro_named_only": "This polymer has no recognisable polymerisation linkage; showing a likely mechanism only — explicit monomer structures could not be derived.",
        "get_free_api": "Get Free API Key (https://aistudio.google.com/app/apikey)",
        "chatbot_no_api": "To get detailed chemical insights about this polymer, please enter a **Google Gemini API Key** in the left menu.",
        "chatbot_desc": "Use the AI-powered ChatBot to get detailed chemical insights about the polymer structure and predicted properties.",
        "download":"Download",
        "report_ready": "Report is ready!",
        "report_getting_ready": "Report is being compiled... Please wait.",
        "pdf_report_info": "This report includes all predictions, molecular structure, AI insights, and any proposed synthesis plans.",
        "pdf_report": "PDF Report",
        "how_to_read": """                **How to Read These Charts?**
                * **Convergence (Top):** The green line should steadily decrease and eventually plateau. If the blue line closely follows the green, it indicates the population is "learning".
                * **Diversity (Bottom):** The red line should not drop to zero too quickly. If it does, the model has fallen into a "Premature Convergence" trap, meaning it has settled on a solution without adequately exploring the search space.""",
        "genetic_algorithm_report": "Genetic Algorithm Performance Report",
        "novelty_explanation": "*Similarity is calculated using the Tanimoto Index (Morgan Fingerprints).*",
        "closest_sim": "Closest Similarity",
        "novel":"**DISCOVERY:** This structure is NOT in the training set! A completely novel design.",
        "benzer_yapi": "View Similar Structure",
        "turev": "**Derivative:** Very similar to a structure in the training set.",
        "benzer":"Similar Record:",
        "copy":"**Copy:** The AI has memorized a data point from the training set.",
        "kayitli": "This molecule is registered in PubChem:",
        "code":"code",
        "radar_warning":"Radar chart requires at least 3 properties (e.g., Tg, LOI, CTE).",
        "takip_disi":"Out of Target",
        "water": "Water",
        "metanol": "Methanol",
        "etanol": "Ethanol",     
        "THF": "Tetrahydrofuran (THF)",
        "diklorometan": "Dichloromethane (DCM)",
        "aseton": "Acetone (Polar Aprotic)",
        "kloroform": "Chloroform",
        "etil asetat": "Ethyl Acetate",
        "toluen": "Toluene (Aromatic)",
        "dietil_eter": "Diethyl Ether",
        "hekzan": "Hexane",
        "solubility_explanation_1": "*The analysis is based on the Hansen Parameter difference between the Polymer ",
        "solubility_explanation_2": " and Solvent, following the 'Like Dissolves Like' principle.*",
        "no_solubility":"This polymer looks very resistant (or requires a very specific solvent).",
        "aromatic":"High Aromaticity (Difficult to Degrade)",
        "halogen":"Number of Halogen atoms (Persistence/Toxicity risk)",
        "ether":"Ether group (Hydrophilic character)",
        "amide":"Amide bond (Biodegradability potential)",
        "ester":"Ester bond (Hydrolyzable)",
        "easy": "Easy",
        "hard": "Hard",
        "best_fitness": "Best Fitness",
        "avg_fitness": "Average (Valid)",
        "survival_rate": "Survival Rate %",
        "gen": "Generation",
        "diversity_chart": "Population Diversity",
        "convergence_chart": "Convergence Analysis",
        "evolution_panel": "### 🧬 Evolutionary Process Tracking Panel",
        "api_key_explanation": "You can get a free key from https://aistudio.google.com/app/apikey to get AI feedback.",
        "target": "Target",
        # General Titles
        "app_subtitle": "AI-Powered Polymer Designer",
        "sidebar_target_selection": "Target Selection",
        "sidebar_included_props": "Properties to Include",
        "sidebar_target_values": "Target Values",
        "sidebar_generations": "Number of Generations",
        "sidebar_strategy": "Algorithm Strategy",
        "manual_title": "Manual Polymer Analysis",
        "manual_desc": "Quickly get the predicted properties and retrosynthesis for your own polymer (SMILES) without running the genetic algorithm.",
        "manual_input_label": "Polymer SMILES (e.g. *CC(c1ccccc1)*):",
        "manual_btn": "Analyze",
        "manual_invalid": "Invalid SMILES. Please check the chemical syntax.",
        "xtb_header": "Quantum cross-check (xtb / GFN2)",
        "xtb_desc": "Computes the band gap and electronic polarizability with an independent semi-empirical quantum method (GFN2-xTB). Shown only when xtb is installed locally.",
        "xtb_btn": "Verify with xtb",
        "xtb_running": "Running xtb (embedding oligomers in 3D and computing)…",
        "xtb_failed": "xtb cross-check could not complete",
        "xtb_gap_label": "xtb band gap (infinite chain)",
        "xtb_model_label": "Model prediction",
        "xtb_polar_label": "Electronic polarizability density (α/V)",
        "xtb_polar_hint": "Higher ⇒ higher refractive index & dielectric (ranking indicator)",
        "xtb_note": "GFN2 is semi-empirical; its absolute value sits systematically off the training DFT — rank agreement is the metric. Details: validation/XTB_VALIDATION.md",
        "verify_title": "Verify this result (quantum)",
        "verify_desc": "Cross-check the optimal polymer's predictions with INDEPENDENT methods: van Krevelen group-contribution (solubility, Hansen, refractive index) always, plus GFN2-xTB quantum chemistry (band gap, dielectric floor) when xtb is installed.",
        "verify_btn": "Verify with independent methods",
        "verify_none": "No independently-verifiable property was found for this polymer.",
        "verify_independent": "independent estimate",
        "verify_floor": "physical floor",
        "blend_misc_miscible": "miscible",
        "blend_misc_borderline": "borderline",
        "blend_misc_immiscible": "immiscible",
        "blend_misc_unknown": "undetermined",
        "blend_misc_note_miscible": "Solubility parameters are close; a single Tg is expected.",
        "blend_misc_note_borderline": "Partial miscibility / weak interphase; expect a broadened Tg or two close Tgs.",
        "blend_misc_note_immiscible": "Phase separated; expect two Tgs. This is not necessarily bad — most toughened commercial materials rely on a dispersed rubber phase.",
        "blend_misc_note_crystalline": "Solubility parameters match, BUT both components appear semi-crystalline: separate crystalline phases normally persist in the solid state regardless (PE/PP is the classic example). Expect phase separation on cooling.",
        "blend_misc_note_unknown": "Solubility parameters could not be derived for one of the components.",
        "blend_misc_caveat_specific": "CAUTION: a specific interaction is possible here ({inter}); solubility parameters cannot capture it, and it can force miscibility.",
        "blend_inter_pipi": "aromatic ether + aromatic ring (π-π, e.g. PPO/PS)",
        "blend_inter_dipole": "carbonyl + halogenated carbon (dipole/H-bond, e.g. PMMA/PVDF)",
        "blend_inter_hbond": "hydroxyl + carbonyl (H-bond)",
        "blend_rule_fox": "Fox equation (miscible)",
        "blend_rule_phasesep": "phase separated",
        "blend_rule_specvol": "additive specific volume",
        "blend_rule_ll": "Lorentz-Lorenz (volume fraction)",
        "blend_rule_semilog": "semi-log additive (miscible)",
        "blend_rule_maxwell": "Maxwell model (dispersed phase)",
        "blend_rule_volfrac": "volume-fraction additive",
        "blend_rule_wtadd": "weight additive",
        "blend_rule_weakest": "least-stable component",
        "blend_rule_notavg": "not averaged",
        "blend_rule_rom": "rule of mixtures (parallel bound)",
        "blend_note_singletg": "single Tg expected",
        "blend_note_twotg": "two Tgs retained: {tgs}",
        "blend_note_hazy": "phase-separated blends scatter light and are usually hazy",
        "blend_note_continuous": "continuous phase = component {n}",
        "blend_note_loi": "CAUTION: flame retardancy is often non-additive (synergism/antagonism); treat as indicative only.",
        "blend_note_td": "decomposition onset is governed by the weakest component",
        "blend_note_tm_each": "each crystalline phase keeps its own Tm: {tms}",
        "blend_note_bounds": "series bound {ser}; the true value lies between the bounds and depends on morphology",
        "blend_mode": "Combination type",
        "blend_mode_blend": "Blend (physical mixture)",
        "blend_mode_random": "Random copolymer",
        "blend_mode_alternating": "Alternating copolymer",
        "blend_mode_block": "Block copolymer",
        "copo_built_unit": "Constructed A-B repeat unit (predicted directly by the models):",
        "copo_rule_direct": "direct prediction (real repeat unit)",
        "copo_rule_fox": "Fox equation (single phase)",
        "copo_rule_wtadd": "weight additive",
        "copo_rule_semilog": "semi-log additive",
        "copo_rule_weakest": "least-stable component",
        "copo_rule_twophase": "two phases (microphase separation)",
        "copo_rule_nocryst": "crystallinity disrupted",
        "copo_note_alternating_exact": "In an alternating copolymer the A-B pair IS a real repeat unit, so it was constructed and handed straight to the models — this is a direct prediction, not a mixing estimate.",
        "copo_note_build_failed": "The A-B repeat unit could not be constructed (one component is not a well-formed repeat unit).",
        "copo_note_block_sep": "The blocks microphase-separate: expect two Tgs and a domain morphology. This is exactly what makes SBS a thermoplastic elastomer.",
        "copo_note_block_single": "The blocks look miscible: expect a single phase and one Tg.",
        "copo_note_two_tg": "two Tgs retained: {tgs}",
        "copo_note_td": "decomposition onset is governed by the weakest component",
        "copo_note_tm_suppressed": "Comonomer incorporation destroys chain regularity, so the melting point is SUPPRESSED (or lost) rather than averaged. That is why EVA is flexible where PE is not.",
        "copo_note_tm_each": "each crystalline phase keeps its own Tm: {tms}",
        "tab_blend": "Blend",
        "blend_header": "Polymer blend / alloy",
        "blend_desc": "Real materials are usually blends or alloys, not neat homopolymers (Noryl = PS/PPO, ABS, PC/ABS). Blend this result with a commodity polymer or another candidate: the miscibility is screened and blend properties estimated with standard mixing rules.",
        "blend_partner": "Blend partner",
        "blend_custom": "or enter your own SMILES (optional)",
        "blend_weight": "Weight fraction of the main polymer (%)",
        "blend_miscibility": "Miscibility",
        "blend_confidence": "confidence",
        "blend_props": "Blend properties",
        "blend_value": "Value",
        "blend_rule": "Rule used",
        "blend_note": "Note",
        "blend_candidate": "Candidate",
        "blend_download": "Download blend data (CSV)",
        "blend_screen_caveat": "This is a SCREEN, not a proof: solubility parameters capture only the enthalpic term. Pairs held together by specific interactions (PS/PPO π-π, PMMA/PVDF dipole) can be mis-called — those are flagged separately. Measured 7/10 on textbook blends.",
        "cr_bad_smiles": "SMILES does not parse to a valid molecule.",
        "cr_need_two_stars": "A repeat unit needs two connection points '*'.",
        "cr_multistar": "{n} connection points: this is a branch/crosslink junction, not a linear repeat unit. Properties assume a linear chain and will shift once the network forms.",
        "cr_acid_alcohol": "Carries both -COOH and -OH: these will self-esterify on processing, so this is not a stable repeat unit (it would branch/crosslink or keep polymerising).",
        "cr_acid_amine": "Carries both -COOH and -NH: will self-amidate on heating; not a stable repeat unit.",
        "cr_epoxide": "An epoxide together with a nucleophile (-OH/-NH/-COOH) will ring-open and crosslink.",
        "cr_isocyanate": "Free isocyanate is highly reactive and moisture sensitive; it would not persist in an isolated polymer.",
        "cr_peroxide": "Peroxide linkage: thermally unstable/explosive.",
        "cr_nn_bond": "Acyclic N-N bond: usually thermally labile.",
        "cr_tm_amorphous": "Tm is reported ({tm} °C) but this structure looks AMORPHOUS (bulky pendant / hindered backbone). An amorphous polymer has no melting point — treat Tm as meaningless here and use Tg. Note tacticity is not encoded in a repeat unit, so this is a structural inference.",
        "cr_tm_plausible": "The backbone looks regular enough to crystallise, so Tm is plausible — but crystallinity also depends on tacticity and thermal history, which a repeat unit cannot express.",
        "cr_tg_above_tm": "Tg ({tg} °C) is not below Tm ({tm} °C); for a semi-crystalline polymer Tg < Tm always holds, so at least one of the two predictions is off.",
        "cr_tg_above_td": "Tg ({tg} °C) is above Td ({td} °C): a polymer cannot soften above the temperature at which it decomposes, so one of these two predictions is wrong for this structure.",
        "cr_tm_above_td": "Tm ({tm} °C) is above Td ({td} °C): the polymer would decompose before melting, so it has no accessible melt window (and one of the two predictions is likely wrong).",
        "cr_boyer_beaman": "Tg/Tm = {ratio} in K; the Boyer-Beaman rule puts most polymers at 0.5-0.8, so this pair is unusual.",
        "cr_halogen_loi": "High LOI here comes from halogen content. Halogenated flame retardancy is effective but is being regulated out in many markets (and Br/Cl release corrosive HX on combustion).",
        "cr_very_aromatic": "Heavily aromatic: likely poor solubility and a very high processing temperature; melt processing may not be possible.",
        "cr_big_unit": "Large repeat unit ({mw} g/mol): a multi-step monomer synthesis is implied.",
        "chem_review_title": "Chemist's review",
        "chem_review_desc": "The models return a number for every structure, and some of those numbers are physically meaningless for this particular polymer (a melting point for an amorphous one). These notes flag those cases and any groups that would not survive as a stable repeat unit. They are cautions, not rejections.",
        "topn_title": "Other strong candidates",
        "topn_desc": "The lowest-error polymer is not always the easiest to make. These candidates also hit your targets closely — some may be far simpler to synthesise (lower SA score) or built from more familiar chemistry.",
        "topn_download": "Download candidate list (CSV)",
        "mae_heldout": "Measured on a 20% hold-out — a genuine out-of-sample error, but in-distribution, so slightly optimistic versus the golden-set number.",
        "mae_molecule": "Uncertainty specific to THIS molecule, from the model's own internal spread (validated to actually predict error for this property). The ＊ marks a molecule-level value.",
        "stay_in_domain": "Stay in the model's confidence zone",
        "stay_in_domain_help": "When on, the GA penalises polymers far from the training data (where predictions are untrustworthy). OFF BY DEFAULT: it reduces novelty in exchange for more reliable predictions.",
        "stay_in_domain_note": "Trade-off: more reliable predictions, less novel structures.",
        "pubchem_search": "Search on PubChem",
        "verify_branched": "This repeat unit is branched (more than 2 connection points). The xtb check runs on the main chain with the branches capped off; van Krevelen uses every atom.",
        "verify_note": "✅ consistent · ⚠️ borderline · ❌ diverges. Band gap is a calibrated absolute check (±0.9 eV, xtb). Refractive index / solubility / Hansen are group-contribution estimates (van Krevelen). The remaining properties (Tg, Tm, Td, CTE…) have no reliable single-polymer oracle — trust the model with the golden-set error bar. Details: validation/",
        "mae_legend": "± is the typical error to expect for a NEW polymer, not a confidence interval. Hover a value for its source.",
        "mae_gold": "Out-of-sample: mean absolute error measured on 18 canonical reference polymers (the honest estimate).",
        "mae_insample": "In-sample / held-out error only — optimistic, treat as a lower bound.",
        "ad_title": "Applicability domain",
        "ad_ok": "this polymer resembles the training data; predictions carry their normal accuracy",
        "ad_warn_edge": "this polymer sits at the EDGE of the training data. Use absolute values with caution; direction/ranking is more reliable.",
        "ad_warn_out": "this polymer is OUTSIDE the training distribution (extrapolation). EPS in particular reverts to the mean out-of-domain — do not trust absolute values; use the direction/ranking and run the verification panel if you can.",
        "ad_similarity": "nearest-training-set similarity",
        "retro_exact": "Exact: re-polymerising this monomer reproduces this repeat unit precisely.",
        "retro_approx": "Approximate: the monomer is the nearest realistic one; re-polymerising gives a close but not identical unit.",
        "btn_download_report": "Download full report (.txt)",
        "start_from": "Start from your own polymer (SMILES, optional)",
        "start_from_help": "Enter a SMILES and the GA will improve THAT polymer instead of starting from scratch. Leave empty to start from the dataset as usual.",
        "start_from_invalid": "Invalid polymer SMILES (needs two '*' connection points) — ignoring it.",
        "start_from_ok": "Starting polymer accepted.",
        "start_from_compare": "Change vs your starting polymer",
        "start_from_prop": "Property",
        "start_from_before": "Start",
        "start_from_after": "Result",
        "random_seed": "Random seed (0 = random)",
        "random_seed_help": "A non-zero value makes a run with the same settings reproduce the same result every time (reproducibility).",
        "ga_params_title": "Advanced GA Parameters",
        "ga_pop_size": "Population size",
        "ga_pop_size_help": "Number of candidate polymers per generation. Larger = better search but slower. (Rounded to a multiple of 4 for NSGA-II.)",
        "ga_cxpb": "Crossover probability",
        "ga_cxpb_help": "Chance two parents swap acyclic substituents (crossover).",
        "ga_fragpb": "Fragment-mutation probability",
        "ga_fragpb_help": "Chance of a goal-directed group/backbone-spacer edit (the primary mutation operator).",
        "ga_mutpb": "SELFIES micro-mutation",
        "ga_mutpb_help": "Chance of a small token-level SELFIES mutation (kept low, for exploration).",
        "ga_chempb": "Reaction mutation",
        "ga_chempb_help": "Chance of a SMARTS reaction-based mutation.",
        "ga_removepb": "Group-trim probability",
        "ga_removepb_help": "Chance of a structure-preserving leaf-group removal (never touches rings/functional groups).",
        "ga_newpb": "New-individual (reseed) probability",
        "ga_newpb_help": "Chance of injecting a fresh random individual for diversity. High values can disrupt the search.",
        "ga_tournsize": "Tournament size",
        "ga_tournsize_help": "Selection pressure: larger = faster convergence but less diversity.",
        "ga_reset": "Reset to defaults",
        "reliability_legend": "Model reliability: 🟢 high · 🟡 medium · 🟠 ranking only · 🔴 unreliable (from validation on the dataset)",
        "reliability_high": "High reliability — the model predicts this property well on the dataset.",
        "reliability_medium": "Medium reliability — roughly right, with meaningful uncertainty on the absolute value.",
        "reliability_low": "Low reliability — use for ranking only; don't trust the absolute value.",
        "reliability_unreliable": "Unreliable — this model failed validation (data/label problem). Do not trust the result.",
        "warn_unreliable": "The model for these properties is unreliable; targeting them may be misleading:",
        "opt_mode": "Optimization Mode",
        "opt_mode_help": "NSGA-II: multi-objective Pareto optimization; keeps the trade-offs between competing targets. Weighted: the classic single-score method that collapses every error into one number.",
        "opt_nsga2": "NSGA-II (Pareto / Multi-objective)",
        "opt_weighted": "Weighted (Single-objective)",
        "pareto_front": "Pareto Front (Trade-off Solutions)",
        "pareto_desc": "Each row is a non-dominated polymer candidate offering a different trade-off between the targets.",
        "knee_note": "**⭐ Knee point:** the solution that balances all targets best — this is the result shown above.  🎯 = lowest total error (may be strong on one property but lopsided).",
        "knee_point": "Knee point (most balanced)",
        "col_pick": "Pick",
        "use_heuristic": "Heuristic Start (Goal-guided)",
        "use_heuristic_help": "On: the population is seeded with base polymers that match the goal (e.g. flexible backbones for low Tg) and mutations are steered toward the target. Off: the classic 'blind' start (random from the dataset only).",
        "preserve_structure": "Preserve Key Structures",
        "preserve_structure_help": "On: mutations can never destroy existing rings, aromatic systems or functional groups (ester, amide, imide, sulfone, ...); they may only add to them.",
        "sidebar_llm_settings": "LLM ChatBot Settings",
        "sidebar_btn_search": "Search Target",
        
        # Warnings and Messages
        "warn_no_target": "Please select at least one target to optimize.",
        "warn_empty_pop": "Initial population is empty or invalid.",
        "msg_optimizing": "Genetic Algorithm Running... Targets:",
        "msg_success": "✅ Optimization Completed Successfully!",
        "msg_ai_thinking": "AI is thinking...",
        
        # Properties
        "prop_tg": "Tg (Glass Transition Temp.)",
        "prop_td": "Td (Decomposition Temp.)",
        "prop_eps": "EPS (Dielectric Constant)",
        "prop_tm": "Tm (Melting Temp.)",
        "prop_bandgap_bulk": "Bandgap Bulk",
        "prop_bandgap_chain": "Bandgap Chain",
        "prop_bandgap_crystal": "Bandgap Crystal",
        "prop_gas_perma": "Gas Permeability",
        "prop_refractive": "Refractive Index",
        "prop_loi": "LOI (Limiting Oxygen Index)",
        "prop_solubility": "Solubility (Hildebrand)",
        "prop_thermal_cond": "Thermal Conductivity",
        "prop_cte": "Coefficient of Thermal Expansion (CTE)",
        "prop_recyclability": "Chemical Recyclability (ΔH_rop)",
        "prop_degradability": "Degradability Score",
        "prop_hansen": "Hansen Solubility Parameter",
        
        # Tabs
        "tab_general": "Overview",
        "tab_structural": "Structural Analysis",
        "tab_evolution": "Evolution History",
        "tab_report": "Reporting",
        "tab_chatbot": "ChatBot",
        "tab_retro": "Retrosynthesis",
        
        # Metrics & Analysis
        "metric_total_error": "Total Error:",
        "metric_sa_score": "Synthetic Accessibility (SA)",
        "metric_green_score": "Green Score",
        "env_analysis": "Environmental Analysis:",
        "solubility_analysis": "Estimated Solubility Analysis",
        "soluble_in": "Expected to Dissolve In:",
        "swelling_in": "Expected to Swell / Hardly Dissolve In:",
        "radar_title": "Target Compatibility Analysis",
        
        # Tabs 2 & 3
        "2d_structure": "2D Structure (Technical Drawing)",
        "3d_structure": "3D Structure (Conformation)",
        "novelty_search": "Novelty Search",
        "similarity_to_train": "Similarity to Training Set",
        "convergence_chart": "Convergence Analysis",
        "diversity_chart": "Population Diversity",
        
        # Reporting
        "report_header": "Reporting",
        "report_desc": "You can export project data as a CSV or a detailed PDF report.",
        "btn_download_csv": "Download Dataset (.csv)",
        "btn_create_pdf": "Generate PDF Report",
        
        # Retrosynthesis
        "retro_structural": "1. Structural Decomposition",
        "retro_t5_pred": "2. T5-Model Prediction",
        "btn_predict_monomer": "Predict Monomers",
        "proposed_monomers": "Proposed Monomers:"
    }
}
